import './globals.css';
import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const Modal = dynamic(() => import('@/common/components/modal/index'));

export const metadata: Metadata = {
  title: 'Pomolite',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.ico',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Modal />
        {children}
      </body>
    </html>
  );
}
